name: OpenGrep Full Scan

on:
  workflow_dispatch:
  pull_request:   

jobs:
  scan:
    name: Scan with OpenGrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Step 2: Download and install OpenGrep
      - name: Install OpenGrep
        run: |
          # Download the OpenGrep binary
          wget https://github.com/opengrep/opengrep/releases/download/v1.0.0-alpha.9/opengrep_manylinux_x86 -O opengrep
          
          # Make the binary executable
          chmod +x opengrep

          # Move the binary to a directory in PATH
          sudo mv opengrep /usr/local/bin/opengrep

      # Step 3: Define custom rules and run OpenGrep
      - name: Run OpenGrep with custom rules
        run: |
          # Define your custom rules (e.g., TODO, FIXME, debug statements)
          RULES="TODO|FIXME|console\.log|print_r|var_dump|API_KEY|PASSWORD|SECRET"

          # Run OpenGrep with the custom rules
          output=$(opengrep "$RULES")

          # Check if any matches were found
          if [ -n "$output" ]; then
            echo "::error::OpenGrep found issues in the codebase:"
            echo "$output"
            exit 1  # Fail the workflow if issues are found
          else
            echo "No issues found. Codebase is clean!"
          fi